### ISSUE TITLE
大佬，能分享下驱动的源码吗，

### ISSUE THREAD

**Issue by xindanci** [qiuapeng921/DnfHelper#2]
最近在写内核驱动，有一些疑问，看看能不能从其他代码中找到解决方案，万望回复一下

**Comment by code-gopher** [comment]
> 最近在写内核驱动，有一些疑问，看看能不能从其他代码中找到解决方案，万望回复一下

我没有驱动源码 都是别人写好的成品

**Comment by xindanci** [comment]
好吧
